[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'forge-cache'

optimizer = true
optimizer_runs = 200

[fuzz]
runs = 256
max_test_rejects = 10240000