[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'forge-cache'

optimizer = true
optimizer_runs = 1500

[fuzz]
runs = 1000
max_test_rejects = 2560000